DATA_FILE = "/data_storage/data.csv"
MAX_LINES = 7000
LOG_INTERVAL_SECONDS = 10

# Sensor Field Names
CO2_PPM = "co2_ppm"
ERROR = "error"
HUMIDITY = "humidity"
STATUS = "status"
TEMPERATURE = "temperature"
TIMESTAMP = "timestamp"
FIELDNAMES = [TIMESTAMP, CO2_PPM, TEMPERATURE, HUMIDITY]

# Sensor Params
S2C_FREQUENCY = 50000
REFERENCE_LEVEL_CO2_PPM = 425
SAMPLING_INTERVAL_SECONDS = 10
WAIT_INTERVAL_SECONDS = 1

# HomeKit
HOMEKIT_STATE_DIR = "/homekit_state"
HOMEKIT_STATE_FILE = f"{HOMEKIT_STATE_DIR}/accessory.state"
HOMEKIT_PORT = 51826
HOMEKIT_POLL_INTERVAL_SECONDS = 10
CO2_ABNORMAL_THRESHOLD_PPM = 1000
HOMEKIT_BRIDGE_NAME = "PiWheeze"
HOMEKIT_MANUFACTURER = "CptStubbs"
HOMEKIT_MODEL = "PiWheeze-SCD30"